// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'pokemon_url_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'pokemon_url_model.g.dart';

@freezed
class PokemonUrlModel with _$PokemonUrlModel {
  const factory PokemonUrlModel({
    required String name,
    required String url,
  }) = _PokemonUrlModel;

  factory PokemonUrlModel.fromJson(Map<String, Object?> json) => _$PokemonUrlModelFromJson(json);
}
