// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'pokemon_sprites_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'pokemon_sprites_model.g.dart';

@freezed
class PokemonSpritesModel with _$PokemonSpritesModel {
  const factory PokemonSpritesModel({
    required String front_default,
    String? front_shiny,
    String? back_default,
    String? back_shiny,
  }) = _PokemonSpritesModel;

  factory PokemonSpritesModel.fromJson(Map<String, Object?> json) => _$PokemonSpritesModelFromJson(json);
}
